---
- hosts: localhost
  vars:
    clion_version: 2016.2.2
  tasks:
  - stat: path=/opt/jetbrains/downloads/CLion-{{ clion_version}}.tar.gz
    register: clion_downloaded
  - name: Create /opt/jetbrains/downloads/
    file: path=/opt/jetbrains/downloads/ state=directory owner=fedora group=fedora mode=0755
    become: true
    become_user: root
  - name: Create /opt/jetbrains/clion/
    file: path=/opt/jetbrains/clion/ state=directory owner=fedora group=fedora mode=0755
    become: true
    become_user: root
  - name: download clion
    get_url:
      url: https://download-cf.jetbrains.com/cpp/CLion-{{ clion_version }}.tar.gz
      dest: /opt/jetbrains/downloads/CLion-{{ clion_version}}.tar.gz
    when: clion_downloaded.stat.exists == False
  - name: extract clion
    shell: "tar xzf /opt/jetbrains/downloads/CLion-{{ clion_version}}.tar.gz -C /opt/jetbrains/clion --strip-components=1"
    become: true
    become_user: root
  - name: Create symlink for clion
    file: src=/opt/jetbrains/clion/bin/clion.sh dest=/usr/local/bin/clion state=link
    become: true
    become_user: root

