---
- hosts: localhost
  vars:
    gitkraken_version: 1.6.1
  tasks:
  - name: Create /opt/axosoft
    file: path=/opt/axosoft state=directory owner=fedora group=fedora mode=0755
    become: true
    become_user: root
  - name: Create /opt/axosoft/downloads
    file: path=/opt/axosoft/downloads state=directory owner=fedora group=fedora mode=0755
    become: true
    become_user: root
  - name: download gitkraken
    get_url:
      url: https://release.gitkraken.com/linux/gitkraken-amd64.tar.gz
      dest: /opt/axosoft/downloads/gitkraken-{{gitkraken_version}}.linux.tar.gz
  - unarchive: src=/opt/axosoft/downloads/gitkraken-{{gitkraken_version}}.linux.tar.gz dest=/opt/axosoft  
  - name: Create symlink for GitKraken
    file: src=/opt/axosoft/GitKraken/gitkraken dest=/usr/local/bin/gitkraken state=link
    become: true
    become_user: root

