---
- hosts: vms
  vars:
    intellij_version: 2017.1
  tasks:
  - stat: path=/opt/jetbrains/downloads/ideaIU-{{ intellij_version }}.tar.gz
    register: idea_downloaded
  - name: Create /opt/jetbrains/downloads/
    file: path=/opt/jetbrains/downloads/ state=directory owner=fedora group=fedora mode=0755
    become: true
    become_user: root
  - name: Create /opt/jetbrains/idea/
    file: path=/opt/jetbrains/idea/ state=directory owner=fedora group=fedora mode=0755
    become: true
    become_user: root
  - name: download intellij
    get_url:
      url: https://download.jetbrains.com/idea/ideaIU-{{ intellij_version }}.tar.gz
      dest: /opt/jetbrains/downloads/ideaIU-{{ intellij_version }}.tar.gz
    when: idea_downloaded.stat.exists == False
  - name: extract intellij
    shell: "tar xzf /opt/jetbrains/downloads/ideaIU-{{ intellij_version }}.tar.gz -C /opt/jetbrains/idea --strip-components=1"
    become: true
    become_user: root
  - name: Create symlink for intellij
    file: src=/opt/jetbrains/idea/bin/idea.sh dest=/usr/local/bin/idea state=link
    become: true
    become_user: root

