---
- hosts: localhost
  vars:
    rubymine_version: 2016.2.3
  tasks:
  - stat: path=/opt/jetbrains/downloads/RubyMine-{{ rubymine_version}}.tar.gz
    register: rubymine_downloaded
  - name: Create /opt/jetbrains/downloads/
    file: path=/opt/jetbrains/downloads/ state=directory owner=fedora group=fedora mode=0755
    become: true
    become_user: root
  - name: Create /opt/jetbrains/rubymine/
    file: path=/opt/jetbrains/rubymine/ state=directory owner=fedora group=fedora mode=0755
    become: true
    become_user: root
  - name: download rubymine
    get_url:
      url: https://download-cf.jetbrains.com/ruby/RubyMine-{{ rubymine_version}}.tar.gz
      dest: /opt/jetbrains/downloads/RubyMine-{{ rubymine_version}}.tar.gz
    when: rubymine_downloaded.stat.exists == False
  - name: extract rubymine
    shell: "tar xzf /opt/jetbrains/downloads/RubyMine-{{ rubymine_version}}.tar.gz -C /opt/jetbrains/rubymine --strip-components=1"
    become: true
    become_user: root
  - name: Create symlink for rubymine
    file: src=/opt/jetbrains/rubymine/bin/rubymine.sh dest=/usr/local/bin/rubymine state=link
    become: true
    become_user: root

